### ISSUE TITLE
Facturar, añadir líneas

### ISSUE THREAD

**Issue by anacid** [anacid/Fuenlamotor#13]
He probado en una factura a añadir una línea y al imprimar si parece como que lo monta.
Paso las pantallas
![ScreenClip.png](https://zube.io/files/anacid/6e7ceb792ba0fc42801ddb5e4cbb69e2.png)
![ScreenClip.png](https://zube.io/files/anacid/255a39dd3c219ea73b32b0db6ce641a2.png)
![ScreenClip.png](https://zube.io/files/anacid/8faf7b6d98f52daac1709a031e2f7576.png)

**Comment by gregorioruiz** [comment]
Hay que ampliar la altura de la línea de detalle y mirar en la documentación cómo se hace para que eso sea automático.
El cambio hay que hacerlo en el servidor de producción.

**Comment by anacid** [comment]
Revisar informes facturas en el servidor de ellos.

**Comment by gregorioruiz** [comment]
Han facturado todo Mayo y no han dicho nada, así que lo doy por resuelto.
