### ISSUE TITLE
Un contrato, facturar a dos clientes distintos

### ISSUE THREAD

**Issue by anacid** [anacid/Fuenlamotor#14]
He estado probando:
1º.- Desde el contrato al hacer albarán, se puede seleccionar el cliente, pero si creamos dos albaranes distintos, lo agrupa en un solo albarán.
2º.- Hago un albarán desde "albaranes", pero no puedo seleccionar el contrato.
3º.- Hago una factura desde "facturas", y tampoco se puede seleccionar el contrato.

No veo como lo puedo hacer.

**Comment by gregorioruiz** [comment]
Ahora, desde un contrato mensual, deja hacer varios albaranes.
